from .pharmacology import DrugPKPD
import math

def linear_effect_curve(max_effect):
    return lambda conc: min(max_effect, conc * max_effect)

def sigmoid_effect_curve(ec50, max_effect):
    return lambda conc: max_effect * conc / (ec50 + conc)

def inverse_effect_curve(ec50, min_effect):
    return lambda conc: min_effect / (1 + conc/ec50)

# Representative sample of a comprehensive drug database (real file would have 100+ drugs)
drug_db = {
    # Vasopressors & Inotropes
    "epinephrine": DrugPKPD(
        name="Epinephrine", class_="Vasopressor", route="IV", dose=1.0, units="mg", half_life=2.0, volume_of_distribution=0.2, clearance=15.0, absorption=1.0, protein_binding=0.0, metabolism="Hepatic", elimination="Renal", onset=1, peak=2, duration=10, mechanism="Alpha and beta adrenergic agonist", effect_targets=["heart_rate", "blood_pressure_systolic", "blood_pressure_diastolic"], effect_curve=linear_effect_curve(30), side_effects=["arrhythmia", "hypertension", "anxiety"], interactions=["beta_blockers"], contraindications=["tachyarrhythmia"], monitoring=["heart_rate", "blood_pressure"], pediatric_dose=0.01, geriatric_dose=0.5, notes="First-line for cardiac arrest, anaphylaxis."),
    "norepinephrine": DrugPKPD(
        name="Norepinephrine", class_="Vasopressor", route="IV", dose=1.0, units="mg", half_life=2.5, volume_of_distribution=0.3, clearance=10.0, absorption=1.0, protein_binding=0.0, metabolism="Hepatic", elimination="Renal", onset=1, peak=2, duration=10, mechanism="Alpha-1 adrenergic agonist", effect_targets=["blood_pressure_systolic", "blood_pressure_diastolic"], effect_curve=linear_effect_curve(25), side_effects=["ischemia", "hypertension", "arrhythmia"], interactions=["MAOIs"], contraindications=["mesenteric ischemia"], monitoring=["blood_pressure", "perfusion"], pediatric_dose=0.05, geriatric_dose=0.5, notes="First-line for septic shock."),
    "dopamine": DrugPKPD(
        name="Dopamine", class_="Inotrope/Vasopressor", route="IV", dose=5.0, units="mg", half_life=2.0, volume_of_distribution=0.4, clearance=12.0, absorption=1.0, protein_binding=0.0, metabolism="Hepatic", elimination="Renal", onset=2, peak=5, duration=15, mechanism="Dopaminergic and adrenergic agonist", effect_targets=["cardiac_output", "heart_rate"], effect_curve=linear_effect_curve(10), side_effects=["tachycardia", "arrhythmia", "nausea"], interactions=["MAOIs"], contraindications=["pheochromocytoma"], monitoring=["heart_rate", "urine_output"], pediatric_dose=2.0, geriatric_dose=2.0, notes="Dose-dependent effects."),
    "dobutamine": DrugPKPD(
        name="Dobutamine", class_="Inotrope", route="IV", dose=5.0, units="mg", half_life=2.5, volume_of_distribution=0.5, clearance=10.0, absorption=1.0, protein_binding=0.0, metabolism="Hepatic", elimination="Renal", onset=2, peak=5, duration=15, mechanism="Beta-1 adrenergic agonist", effect_targets=["cardiac_output", "heart_rate"], effect_curve=linear_effect_curve(8), side_effects=["tachycardia", "arrhythmia", "hypotension"], interactions=["beta_blockers"], contraindications=["hypertrophic cardiomyopathy"], monitoring=["heart_rate", "blood_pressure"], pediatric_dose=2.0, geriatric_dose=2.0, notes="Inotrope for heart failure, shock."),
    # Antihypertensives
    "lisinopril": DrugPKPD(
        name="Lisinopril", class_="ACE Inhibitor", route="PO", dose=10.0, units="mg", half_life=12.0, volume_of_distribution=1.0, clearance=5.0, absorption=0.25, protein_binding=0.0, metabolism="Hepatic", elimination="Renal", onset=60, peak=240, duration=1440, mechanism="ACE inhibitor", effect_targets=["blood_pressure_systolic", "blood_pressure_diastolic"], effect_curve=linear_effect_curve(-15), side_effects=["cough", "hyperkalemia", "angioedema"], interactions=["ARBs", "NSAIDs"], contraindications=["pregnancy", "angioedema"], monitoring=["blood_pressure", "potassium", "creatinine"], pediatric_dose=0.07, geriatric_dose=5.0, notes="First-line for hypertension, heart failure."),
    "amlodipine": DrugPKPD(
        name="Amlodipine", class_="Calcium Channel Blocker", route="PO", dose=5.0, units="mg", half_life=30.0, volume_of_distribution=21.0, clearance=7.0, absorption=0.65, protein_binding=0.98, metabolism="Hepatic", elimination="Renal", onset=240, peak=480, duration=1440, mechanism="Calcium channel blocker", effect_targets=["blood_pressure_systolic", "blood_pressure_diastolic"], effect_curve=linear_effect_curve(-12), side_effects=["edema", "flushing", "dizziness"], interactions=["simvastatin"], contraindications=["severe hypotension"], monitoring=["blood_pressure"], pediatric_dose=2.5, geriatric_dose=2.5, notes="Long-acting antihypertensive."),
    # Antibiotics
    "ceftriaxone": DrugPKPD(
        name="Ceftriaxone", class_="Cephalosporin Antibiotic", route="IV", dose=1000.0, units="mg", half_life=8.0, volume_of_distribution=0.2, clearance=1.0, absorption=1.0, protein_binding=0.85, metabolism="Minimal", elimination="Renal/Biliary", onset=30, peak=60, duration=720, mechanism="Inhibits cell wall synthesis", effect_targets=["immune.crp"], effect_curve=linear_effect_curve(-5), side_effects=["allergy", "diarrhea", "biliary sludging"], interactions=["calcium"], contraindications=["neonates with calcium"], monitoring=["crp", "wbc"], pediatric_dose=50.0, geriatric_dose=1000.0, notes="Broad-spectrum, meningitis, sepsis."),
    "vancomycin": DrugPKPD(
        name="Vancomycin", class_="Glycopeptide Antibiotic", route="IV", dose=1000.0, units="mg", half_life=6.0, volume_of_distribution=0.7, clearance=0.8, absorption=1.0, protein_binding=0.5, metabolism="Minimal", elimination="Renal", onset=60, peak=120, duration=720, mechanism="Inhibits cell wall synthesis", effect_targets=["immune.crp"], effect_curve=linear_effect_curve(-7), side_effects=["nephrotoxicity", "ototoxicity", "red man syndrome"], interactions=["aminoglycosides"], contraindications=["hypersensitivity"], monitoring=["crp", "creatinine", "trough"], pediatric_dose=15.0, geriatric_dose=750.0, notes="MRSA, severe infections."),
    # Sedatives/Analgesics
    "midazolam": DrugPKPD(
        name="Midazolam", class_="Benzodiazepine", route="IV", dose=2.0, units="mg", half_life=2.0, volume_of_distribution=1.1, clearance=6.0, absorption=1.0, protein_binding=0.97, metabolism="Hepatic", elimination="Renal", onset=5, peak=10, duration=60, mechanism="GABA-A agonist", effect_targets=["neurological.glasgow_coma_scale"], effect_curve=linear_effect_curve(-2), side_effects=["respiratory depression", "hypotension", "delirium"], interactions=["opioids", "alcohol"], contraindications=["severe respiratory depression"], monitoring=["gcs", "respiratory_rate"], pediatric_dose=0.05, geriatric_dose=1.0, notes="Sedation, seizures, procedures."),
    "fentanyl": DrugPKPD(
        name="Fentanyl", class_="Opioid Analgesic", route="IV", dose=100.0, units="mcg", half_life=4.0, volume_of_distribution=4.0, clearance=15.0, absorption=1.0, protein_binding=0.8, metabolism="Hepatic", elimination="Renal", onset=2, peak=5, duration=30, mechanism="Mu opioid agonist", effect_targets=["pain"], effect_curve=linear_effect_curve(-5), side_effects=["respiratory depression", "constipation", "nausea"], interactions=["benzodiazepines", "alcohol"], contraindications=["severe respiratory depression"], monitoring=["pain", "respiratory_rate"], pediatric_dose=1.0, geriatric_dose=50.0, notes="Acute pain, sedation."),
    # Anticoagulants/Antiplatelets
    "warfarin": DrugPKPD(
        name="Warfarin", class_="Anticoagulant", route="PO", dose=5.0, units="mg", half_life=40.0, volume_of_distribution=0.14, clearance=0.2, absorption=1.0, protein_binding=0.99, metabolism="Hepatic (CYP2C9)", elimination="Renal", onset=1440, peak=2880, duration=10080, mechanism="Vitamin K antagonist", effect_targets=["hematological.inr"], effect_curve=linear_effect_curve(1.5), side_effects=["bleeding", "skin necrosis"], interactions=["antibiotics", "amiodarone"], contraindications=["pregnancy", "bleeding disorder"], monitoring=["inr", "pt"], pediatric_dose=0.2, geriatric_dose=2.5, notes="Chronic anticoagulation."),
    "aspirin": DrugPKPD(
        name="Aspirin", class_="Antiplatelet", route="PO", dose=81.0, units="mg", half_life=0.25, volume_of_distribution=0.2, clearance=5.0, absorption=0.8, protein_binding=0.9, metabolism="Hepatic", elimination="Renal", onset=30, peak=60, duration=1440, mechanism="COX inhibitor", effect_targets=["hematological.platelet_count"], effect_curve=linear_effect_curve(-10), side_effects=["bleeding", "gastritis", "tinnitus"], interactions=["anticoagulants", "NSAIDs"], contraindications=["active bleeding", "children with viral illness"], monitoring=["platelet_count", "bleeding"], pediatric_dose=10.0, geriatric_dose=40.0, notes="MI, stroke prevention."),
    # Insulin/Oral Hypoglycemics
    "insulin": DrugPKPD(
        name="Insulin", class_="Hormone", route="SC", dose=10.0, units="units", half_life=0.5, volume_of_distribution=0.1, clearance=1.2, absorption=0.7, protein_binding=0.0, metabolism="Hepatic/Renal", elimination="Renal", onset=15, peak=60, duration=240, mechanism="Insulin receptor agonist", effect_targets=["endocrine.blood_glucose"], effect_curve=linear_effect_curve(-40), side_effects=["hypoglycemia", "weight gain"], interactions=["beta_blockers"], contraindications=["hypoglycemia"], monitoring=["glucose"], pediatric_dose=0.5, geriatric_dose=5.0, notes="Type 1/2 diabetes, DKA."),
    "metformin": DrugPKPD(
        name="Metformin", class_="Biguanide", route="PO", dose=500.0, units="mg", half_life=6.0, volume_of_distribution=1.0, clearance=1.0, absorption=0.5, protein_binding=0.0, metabolism="Minimal", elimination="Renal", onset=60, peak=120, duration=720, mechanism="Decreases hepatic glucose production", effect_targets=["endocrine.blood_glucose"], effect_curve=linear_effect_curve(-20), side_effects=["lactic acidosis", "GI upset"], interactions=["contrast dye"], contraindications=["renal failure", "acidosis"], monitoring=["glucose", "creatinine"], pediatric_dose=250.0, geriatric_dose=250.0, notes="Type 2 diabetes."),
    # Psychotropics/Antiepileptics
    "sertraline": DrugPKPD(
        name="Sertraline", class_="SSRI", route="PO", dose=50.0, units="mg", half_life=26.0, volume_of_distribution=20.0, clearance=1.5, absorption=0.5, protein_binding=0.98, metabolism="Hepatic (CYP2C19)", elimination="Renal", onset=1440, peak=2880, duration=10080, mechanism="SSRI", effect_targets=["psychiatric.mood"], effect_curve=linear_effect_curve(1), side_effects=["sexual dysfunction", "GI upset", "serotonin syndrome"], interactions=["MAOIs", "triptans"], contraindications=["MAOI use"], monitoring=["mood", "suicidality"], pediatric_dose=25.0, geriatric_dose=25.0, notes="Depression, anxiety."),
    "lorazepam": DrugPKPD(
        name="Lorazepam", class_="Benzodiazepine", route="IV", dose=2.0, units="mg", half_life=12.0, volume_of_distribution=1.3, clearance=1.0, absorption=1.0, protein_binding=0.85, metabolism="Hepatic", elimination="Renal", onset=5, peak=15, duration=120, mechanism="GABA-A agonist", effect_targets=["neurological.glasgow_coma_scale"], effect_curve=linear_effect_curve(-2), side_effects=["sedation", "respiratory depression", "delirium"], interactions=["opioids", "alcohol"], contraindications=["severe respiratory depression"], monitoring=["gcs", "respiratory_rate"], pediatric_dose=0.05, geriatric_dose=1.0, notes="Anxiety, status epilepticus."),
    # ... (repeat for all major classes, 100+ drugs in total)
}

# In the real implementation, this dictionary would be populated with 100+ drugs, each with detailed PK/PD, effects, side effects, interactions, and monitoring. 